version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.0.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "kafka_docker_topic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  example-producer:
    image: example-producer
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - kafka
    command: bash -c "/app/docker-scripts/wait-for-it.sh zk:2181 -t 90 &&  /app/docker-scripts/wait-for-it.sh kafka:9092 -t 90"
  example-consumer-new:
    image: example-consumer-new
    ports:
      - "8081:8081"
    tty: true
    depends_on:
      - kafka
    command: bash -c "/app/docker-scripts/wait-for-it.sh zk:2181 -t 90 &&  /app/docker-scripts/wait-for-it.sh kafka:9092 -t 90"
  example-consumer-old:
    image: example-consumer-old
    ports:
      - "8082:8082"
      - "5005:5005"
    tty: true
    depends_on:
      - kafka
    command: bash -c "/app/docker-scripts/wait-for-it.sh zk:2181 -t 90 &&  /app/docker-scripts/wait-for-it.sh kafka:9092 -t 90"